### ISSUE TITLE
Reload triggers?

### ISSUE THREAD

**Issue by mrc4tt** [sp0ok3r/node-SPKSteamBot#1]
Hi.

If i'm using your bot. is it so possible to make "Triggers"?

As example:

!cmds > bot saying: This commands can be used: !owner, !bla, !test.

And if i will update the !cmds without to restart the script, for the BOT has reloaded script.

**Comment by mrc4tt** [comment]
@sp0ok3r - do you have idea about that?

**Comment by sp0ok3r** [comment]
yes
